In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import pickle

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
import matplotlib.font_manager
from matplotlib import style
style.use('ggplot') or plt.style.use('ggplot')

# Preprocesado y modelado
# ==============================================================================
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')

In [10]:
health_images = np.zeros(shape=(3, 2))
with open('gray_health_images_vector.pickle','rb') as file:
    health : health_images = pickle.load(file)

health

array([array([[187, 180, 194, ..., 229, 202, 224],
              [170, 163, 177, ..., 191, 199, 221],
              [200, 183, 159, ..., 199, 169, 188],
              ...,
              [172, 161, 160, ..., 151, 167, 154],
              [172, 160, 153, ..., 104, 140, 142],
              [157, 164, 184, ..., 108, 185, 194]], dtype=uint8),
       array([[176, 181, 193, ..., 179, 214, 208],
              [177, 170, 163, ..., 171, 175, 162],
              [154, 171, 186, ..., 165, 152, 151],
              ...,
              [239, 248, 247, ..., 242, 246, 237],
              [245, 242, 244, ..., 247, 245, 247],
              [214, 246, 247, ..., 246, 249, 247]], dtype=uint8),
       array([[246, 247, 248, ..., 249, 247, 246],
              [247, 246, 249, ..., 245, 247, 249],
              [235, 231, 239, ..., 246, 247, 245],
              ...,
              [248, 248, 248, ..., 243, 232, 181],
              [248, 248, 248, ..., 245, 207, 133],
              [248, 248, 248, ..., 248, 220, 1

In [11]:
ill_images = np.zeros(shape=(3, 2))
with open('gray_health_images_vector.pickle','rb') as file:
    ill : ill_images = pickle.load(file)

ill

array([array([[187, 180, 194, ..., 229, 202, 224],
              [170, 163, 177, ..., 191, 199, 221],
              [200, 183, 159, ..., 199, 169, 188],
              ...,
              [172, 161, 160, ..., 151, 167, 154],
              [172, 160, 153, ..., 104, 140, 142],
              [157, 164, 184, ..., 108, 185, 194]], dtype=uint8),
       array([[176, 181, 193, ..., 179, 214, 208],
              [177, 170, 163, ..., 171, 175, 162],
              [154, 171, 186, ..., 165, 152, 151],
              ...,
              [239, 248, 247, ..., 242, 246, 237],
              [245, 242, 244, ..., 247, 245, 247],
              [214, 246, 247, ..., 246, 249, 247]], dtype=uint8),
       array([[246, 247, 248, ..., 249, 247, 246],
              [247, 246, 249, ..., 245, 247, 249],
              [235, 231, 239, ..., 246, 247, 245],
              ...,
              [248, 248, 248, ..., 243, 232, 181],
              [248, 248, 248, ..., 245, 207, 133],
              [248, 248, 248, ..., 248, 220, 1

In [18]:
#feature size
health.shape

(185917,)

In [30]:
health_array = np.Array(185917, 2500)


AttributeError: module 'numpy' has no attribute 'Array'

In [19]:
list_initial_features = []
for i in range(185917):
    list_initial_features.append("feat "+str(i))

list_initial_features

['feat 0',
 'feat 1',
 'feat 2',
 'feat 3',
 'feat 4',
 'feat 5',
 'feat 6',
 'feat 7',
 'feat 8',
 'feat 9',
 'feat 10',
 'feat 11',
 'feat 12',
 'feat 13',
 'feat 14',
 'feat 15',
 'feat 16',
 'feat 17',
 'feat 18',
 'feat 19',
 'feat 20',
 'feat 21',
 'feat 22',
 'feat 23',
 'feat 24',
 'feat 25',
 'feat 26',
 'feat 27',
 'feat 28',
 'feat 29',
 'feat 30',
 'feat 31',
 'feat 32',
 'feat 33',
 'feat 34',
 'feat 35',
 'feat 36',
 'feat 37',
 'feat 38',
 'feat 39',
 'feat 40',
 'feat 41',
 'feat 42',
 'feat 43',
 'feat 44',
 'feat 45',
 'feat 46',
 'feat 47',
 'feat 48',
 'feat 49',
 'feat 50',
 'feat 51',
 'feat 52',
 'feat 53',
 'feat 54',
 'feat 55',
 'feat 56',
 'feat 57',
 'feat 58',
 'feat 59',
 'feat 60',
 'feat 61',
 'feat 62',
 'feat 63',
 'feat 64',
 'feat 65',
 'feat 66',
 'feat 67',
 'feat 68',
 'feat 69',
 'feat 70',
 'feat 71',
 'feat 72',
 'feat 73',
 'feat 74',
 'feat 75',
 'feat 76',
 'feat 77',
 'feat 78',
 'feat 79',
 'feat 80',
 'feat 81',
 'feat 82',
 'feat 83',
 '

TypeError: 'int' object is not callable