In [1]:
import numpy as np
import pandas as pd
#import statsmodels.api as sm
import pickle

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
import matplotlib.font_manager
from matplotlib import style
style.use('ggplot') or plt.style.use('ggplot')

# Preprocesado y modelado
# ==============================================================================
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')

In [2]:
health_images = []
with open('gray_large_health_list.pickle','rb') as file:
    health : health_images = pickle.load(file)

health

[array([187, 180, 194, 193, 184, 187, 175, 178, 195, 171, 145, 153, 138,
        149, 159, 167, 171, 162, 153, 147, 151, 155, 156, 154, 144, 154,
        173, 131, 188, 218, 231, 230, 240, 246, 248, 245, 247, 246, 233,
        209, 202, 196, 178, 198, 211, 223, 221, 229, 202, 224], dtype=uint8),
 array([170, 163, 177, 162, 158, 146, 153, 147, 149, 156, 160, 133, 152,
        145, 153, 151, 155, 150, 158, 153, 146, 141, 143, 161, 138, 152,
        146, 153, 166, 164, 215, 167, 214, 236, 247, 248, 247, 249, 239,
        221, 208, 193, 195, 196, 211, 174, 181, 191, 199, 221], dtype=uint8),
 array([200, 183, 159, 160, 160, 157, 152, 152, 151, 144, 135, 122, 137,
        153, 164, 167, 168, 178, 185, 162, 147, 140, 169, 160, 177, 178,
        167, 171, 203, 149, 157, 224, 213, 236, 244, 239, 202, 175, 167,
        157, 164, 177, 206, 230, 223, 225, 236, 199, 169, 188], dtype=uint8),
 array([184, 186, 188, 181, 176, 189, 191, 162, 154, 154, 167, 174, 183,
        200, 198, 184, 168, 179, 183

In [6]:
health


[array([187, 180, 194, 193, 184, 187, 175, 178, 195, 171, 145, 153, 138,
        149, 159, 167, 171, 162, 153, 147, 151, 155, 156, 154, 144, 154,
        173, 131, 188, 218, 231, 230, 240, 246, 248, 245, 247, 246, 233,
        209, 202, 196, 178, 198, 211, 223, 221, 229, 202, 224], dtype=uint8),
 array([170, 163, 177, 162, 158, 146, 153, 147, 149, 156, 160, 133, 152,
        145, 153, 151, 155, 150, 158, 153, 146, 141, 143, 161, 138, 152,
        146, 153, 166, 164, 215, 167, 214, 236, 247, 248, 247, 249, 239,
        221, 208, 193, 195, 196, 211, 174, 181, 191, 199, 221], dtype=uint8),
 array([200, 183, 159, 160, 160, 157, 152, 152, 151, 144, 135, 122, 137,
        153, 164, 167, 168, 178, 185, 162, 147, 140, 169, 160, 177, 178,
        167, 171, 203, 149, 157, 224, 213, 236, 244, 239, 202, 175, 167,
        157, 164, 177, 206, 230, 223, 225, 236, 199, 169, 188], dtype=uint8),
 array([184, 186, 188, 181, 176, 189, 191, 162, 154, 154, 167, 174, 183,
        200, 198, 184, 168, 179, 183

In [3]:
ill_images = np.zeros(shape=(3, 2))
with open('gray_large_ill_list.pickle','rb') as file:
    ill : ill_images = pickle.load(file)

ill

[array([253, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252,
        252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 251, 251, 251,
        252, 252, 252, 252, 252, 252, 251, 251, 251, 252, 251, 251, 250,
        250, 249, 249, 249, 250, 251, 251, 251, 251, 251, 251], dtype=uint8),
 array([253, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252,
        252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 251, 251, 251,
        252, 252, 252, 252, 252, 252, 251, 251, 251, 251, 252, 251, 251,
        250, 250, 249, 250, 252, 251, 251, 251, 251, 251, 251], dtype=uint8),
 array([252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252,
        252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 251, 251, 251,
        252, 253, 252, 252, 252, 252, 252, 251, 251, 251, 251, 251, 251,
        251, 251, 251, 251, 251, 251, 251, 251, 251, 251, 251], dtype=uint8),
 array([252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252, 252,
        252, 252, 252, 252, 252, 252

In [4]:
#feature size
len(health)

9248623

In [ ]:
health_vector = pd.DataFrame.from_records(health)
health_vector



In [6]:
health_labels = [0 for x in health]
health_labels 
health_vector["cancer"] = health_labels

In [ ]:
health_vector

In [17]:
ill_labels = [1 for x in ill]
ill_labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [18]:
ill_vector["cancer"] = ill_labels

NameError: name 'ill_vector' is not defined

In [30]:
ill_vector

0  \
0       [187, 180, 194, 193, 184, 187, 175, 178, 195, ...   
1       [176, 181, 193, 163, 162, 164, 174, 199, 200, ...   
2       [246, 247, 248, 248, 246, 248, 250, 247, 231, ...   
3       [248, 248, 248, 248, 248, 247, 247, 247, 249, ...   
4       [235, 244, 227, 246, 248, 246, 247, 247, 247, ...   
...                                                   ...   
185912  [88, 84, 99, 92, 101, 105, 142, 175, 179, 216,...   
185913  [240, 217, 220, 224, 230, 232, 238, 195, 242, ...   
185914  [241, 240, 240, 240, 230, 213, 235, 237, 243, ...   
185915  [235, 234, 237, 237, 235, 237, 236, 238, 239, ...   
185916  [194, 178, 132, 183, 219, 225, 229, 212, 221, ...   

                                                        1  \
0       [170, 163, 177, 162, 158, 146, 153, 147, 149, ...   
1       [177, 170, 163, 166, 171, 172, 176, 180, 167, ...   
2       [247, 246, 249, 248, 249, 246, 247, 247, 242, ...   
3       [248, 248, 248, 248, 248, 247, 245, 244, 240, ...   
4       [246, 239, 244, 246, 245, 248, 247, 246, 247, ...   
...                                                   ...   
185912  [120, 108, 94, 107, 98, 114, 139, 145, 124, 16...   
185913  [227, 218, 242, 243, 240, 235, 174, 127, 227, ...   
185914  [240, 241, 241, 241, 239, 226, 208, 193, 214, ...   
185915  [234, 237, 237, 236, 238, 237, 239, 237, 240, ...   
185916  [123, 136, 160, 171, 152, 227, 231, 218, 233, ...   

                                                        2  \
0       [200, 183, 159, 160, 160, 157, 152, 152, 151, ...   
1       [154, 171, 186, 168, 167, 184, 180, 122, 131, ...   
2       [235, 231, 239, 246, 247, 248, 242, 249, 250, ...   
3       [245, 245, 249, 247, 246, 248, 243, 239, 240, ...   
4       [244, 228, 248, 246, 247, 246, 249, 247, 248, ...   
...                                                   ...   
185912  [155, 130, 164, 143, 149, 146, 214, 213, 189, ...   
185913  [203, 236, 242, 238, 240, 242, 200, 123, 180, ...   
185914  [241, 239, 240, 242, 241, 242, 232, 184, 150, ...   
185915  [236, 237, 238, 241, 242, 243, 241, 240, 239, ...   
185916  [151, 188, 170, 131, 193, 240, 237, 187, 229, ...   

                                                        3  \
0       [184, 186, 188, 181, 176, 189, 191, 162, 154, ...   
1       [150, 194, 191, 174, 182, 166, 152, 158, 176, ...   
2       [219, 232, 223, 231, 233, 233, 227, 247, 247, ...   
3       [203, 230, 247, 247, 247, 246, 246, 247, 248, ...   
4       [230, 247, 247, 248, 247, 247, 245, 247, 247, ...   
...                                                   ...   
185912  [126, 101, 125, 119, 155, 162, 162, 117, 121, ...   
185913  [175, 236, 242, 240, 243, 224, 195, 163, 181, ...   
185914  [239, 241, 242, 238, 244, 243, 244, 235, 212, ...   
185915  [236, 235, 237, 240, 241, 244, 242, 241, 239, ...   
185916  [187, 147, 140, 158, 150, 237, 229, 215, 213, ...   

                                                        4  \
0       [191, 181, 178, 186, 192, 188, 181, 190, 195, ...   
1       [173, 172, 162, 164, 168, 176, 163, 150, 140, ...   
2       [238, 236, 244, 229, 216, 203, 192, 211, 246, ...   
3       [201, 201, 243, 244, 247, 229, 241, 226, 192, ...   
4       [233, 247, 245, 248, 246, 247, 248, 235, 216, ...   
...                                                   ...   
185912  [136, 109, 113, 107, 143, 210, 166, 114, 108, ...   
185913  [212, 234, 238, 228, 164, 157, 202, 182, 179, ...   
185914  [242, 242, 243, 243, 246, 244, 239, 244, 242, ...   
185915  [232, 237, 235, 237, 237, 239, 239, 239, 239, ...   
185916  [184, 166, 164, 164, 124, 233, 223, 225, 195, ...   

                                                        5  \
0       [195, 196, 182, 169, 176, 173, 158, 173, 180, ...   
1       [172, 174, 166, 152, 141, 160, 164, 157, 139, ...   
2       [248, 246, 248, 248, 247, 243, 244, 196, 244, ...   
3       [159, 141, 233, 236, 203, 210, 204, 206, 213, ...   
4       [217, 239, 245, 239, 235, 234, 230, 242, 247, ...   
...                      

In [31]:
large_df = pd.concat([health_vector, ill_vector], ignore_index=True)
large_df

0  \
0       [187, 180, 194, 193, 184, 187, 175, 178, 195, ...   
1       [176, 181, 193, 163, 162, 164, 174, 199, 200, ...   
2       [246, 247, 248, 248, 246, 248, 250, 247, 231, ...   
3       [248, 248, 248, 248, 248, 247, 247, 247, 249, ...   
4       [235, 244, 227, 246, 248, 246, 247, 247, 247, ...   
...                                                   ...   
371829  [88, 84, 99, 92, 101, 105, 142, 175, 179, 216,...   
371830  [240, 217, 220, 224, 230, 232, 238, 195, 242, ...   
371831  [241, 240, 240, 240, 230, 213, 235, 237, 243, ...   
371832  [235, 234, 237, 237, 235, 237, 236, 238, 239, ...   
371833  [194, 178, 132, 183, 219, 225, 229, 212, 221, ...   

                                                        1  \
0       [170, 163, 177, 162, 158, 146, 153, 147, 149, ...   
1       [177, 170, 163, 166, 171, 172, 176, 180, 167, ...   
2       [247, 246, 249, 248, 249, 246, 247, 247, 242, ...   
3       [248, 248, 248, 248, 248, 247, 245, 244, 240, ...   
4       [246, 239, 244, 246, 245, 248, 247, 246, 247, ...   
...                                                   ...   
371829  [120, 108, 94, 107, 98, 114, 139, 145, 124, 16...   
371830  [227, 218, 242, 243, 240, 235, 174, 127, 227, ...   
371831  [240, 241, 241, 241, 239, 226, 208, 193, 214, ...   
371832  [234, 237, 237, 236, 238, 237, 239, 237, 240, ...   
371833  [123, 136, 160, 171, 152, 227, 231, 218, 233, ...   

                                                        2  \
0       [200, 183, 159, 160, 160, 157, 152, 152, 151, ...   
1       [154, 171, 186, 168, 167, 184, 180, 122, 131, ...   
2       [235, 231, 239, 246, 247, 248, 242, 249, 250, ...   
3       [245, 245, 249, 247, 246, 248, 243, 239, 240, ...   
4       [244, 228, 248, 246, 247, 246, 249, 247, 248, ...   
...                                                   ...   
371829  [155, 130, 164, 143, 149, 146, 214, 213, 189, ...   
371830  [203, 236, 242, 238, 240, 242, 200, 123, 180, ...   
371831  [241, 239, 240, 242, 241, 242, 232, 184, 150, ...   
371832  [236, 237, 238, 241, 242, 243, 241, 240, 239, ...   
371833  [151, 188, 170, 131, 193, 240, 237, 187, 229, ...   

                                                        3  \
0       [184, 186, 188, 181, 176, 189, 191, 162, 154, ...   
1       [150, 194, 191, 174, 182, 166, 152, 158, 176, ...   
2       [219, 232, 223, 231, 233, 233, 227, 247, 247, ...   
3       [203, 230, 247, 247, 247, 246, 246, 247, 248, ...   
4       [230, 247, 247, 248, 247, 247, 245, 247, 247, ...   
...                                                   ...   
371829  [126, 101, 125, 119, 155, 162, 162, 117, 121, ...   
371830  [175, 236, 242, 240, 243, 224, 195, 163, 181, ...   
371831  [239, 241, 242, 238, 244, 243, 244, 235, 212, ...   
371832  [236, 235, 237, 240, 241, 244, 242, 241, 239, ...   
371833  [187, 147, 140, 158, 150, 237, 229, 215, 213, ...   

                                                        4  \
0       [191, 181, 178, 186, 192, 188, 181, 190, 195, ...   
1       [173, 172, 162, 164, 168, 176, 163, 150, 140, ...   
2       [238, 236, 244, 229, 216, 203, 192, 211, 246, ...   
3       [201, 201, 243, 244, 247, 229, 241, 226, 192, ...   
4       [233, 247, 245, 248, 246, 247, 248, 235, 216, ...   
...                                                   ...   
371829  [136, 109, 113, 107, 143, 210, 166, 114, 108, ...   
371830  [212, 234, 238, 228, 164, 157, 202, 182, 179, ...   
371831  [242, 242, 243, 243, 246, 244, 239, 244, 242, ...   
371832  [232, 237, 235, 237, 237, 239, 239, 239, 239, ...   
371833  [184, 166, 164, 164, 124, 233, 223, 225, 195, ...   

                                                        5  \
0       [195, 196, 182, 169, 176, 173, 158, 173, 180, ...   
1       [172, 174, 166, 152, 141, 160, 164, 157, 139, ...   
2       [248, 246, 248, 248, 247, 243, 244, 196, 244, ...   
3       [159, 141, 233, 236, 203, 210, 204, 206, 213, ...   
4       [217, 239, 245, 239, 235, 234, 230, 242, 247, ...   
...                      

In [33]:
with open("large_dataframe.pickle", "wb") as file:
    pickle.dump(large_df, file)
    

In [9]:
X = health

array([array([[187, 180, 194, ..., 229, 202, 224],
              [170, 163, 177, ..., 191, 199, 221],
              [200, 183, 159, ..., 199, 169, 188],
              ...,
              [172, 161, 160, ..., 151, 167, 154],
              [172, 160, 153, ..., 104, 140, 142],
              [157, 164, 184, ..., 108, 185, 194]], dtype=uint8),
       array([[176, 181, 193, ..., 179, 214, 208],
              [177, 170, 163, ..., 171, 175, 162],
              [154, 171, 186, ..., 165, 152, 151],
              ...,
              [239, 248, 247, ..., 242, 246, 237],
              [245, 242, 244, ..., 247, 245, 247],
              [214, 246, 247, ..., 246, 249, 247]], dtype=uint8),
       array([[246, 247, 248, ..., 249, 247, 246],
              [247, 246, 249, ..., 245, 247, 249],
              [235, 231, 239, ..., 246, 247, 245],
              ...,
              [248, 248, 248, ..., 243, 232, 181],
              [248, 248, 248, ..., 245, 207, 133],
              [248, 248, 248, ..., 248, 220, 1

In [38]:
pca = PCA(n_components=0.5)
compressed_health_images = []

for i in X:
    compressed_health_images.append(pca.fit_transform(i))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (185917,) + inhomogeneous part.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (185917,) + inhomogeneous part.